domain_path: /home/dev/dev/workspace/dds_dma_platform/export/dds_dma_platform/sw/standalone_ps7_cortexa9_0
app_src_dir: /home/dev/build/Xilinx/Vitis/2024.1/data/embeddedsw/lib/sw_apps/lwip_echo_server
template: lwip_echo_server
